"""empty message

Revision ID: 625511d483c2
Revises: 62f006cd937f
Create Date: 2020-01-07 15:55:59.259769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '625511d483c2'
down_revision = '62f006cd937f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'xxx')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('xxx', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
