"""empty message

Revision ID: 914fd1e38099
Revises: e0113664574a
Create Date: 2020-01-07 16:43:18.566398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '914fd1e38099'
down_revision = 'e0113664574a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('zzz', sa.String(length=50), nullable=False))
    op.drop_column('cms_user', 'yyy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('yyy', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_user', 'zzz')
    # ### end Alembic commands ###
