"""empty message

Revision ID: e0113664574a
Revises: 74774f234d12
Create Date: 2020-01-07 16:42:22.319427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0113664574a'
down_revision = '74774f234d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('yyy', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'yyy')
    # ### end Alembic commands ###
